services:
  soc-web-server:
    container_name: soc-web-server 
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: Dockerfile
